landing/urls.py
from django.conf.urls import url
from django.urls import include,path
from django.views.generic import RedirectView
from .views import index,post

urlpatterns = [
    path('',index, name='landing'),
    path('posted',post),
    
]

main_menu/urls.py
from django.contrib import admin
from django.urls import include,path
from django.views.generic import RedirectView
from .views import index

urlpatterns = [
    path('',index)
]

profilku/urls.py
from django.conf.urls import url
from django.urls import include,path
from django.views.generic import RedirectView
from .views import index

urlpatterns = [
    path('',index,name='profilku'),
    
]

story6/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include,path
from django.views.generic import RedirectView

urlpatterns = [
    path('',include(('main_menu.urls','main_menu'),namespace='main_menu')),
    path('admin/', admin.site.urls),
    path('landing/',include(('landing.urls','landing'),namespace='landing')),
    path('profilku/',include(('profilku.urls','profilku'),namespace='profilku')),
  #  path('',RedirectView.as_view(permanent=False, url='/profilku'),name='redirect'),
    
]

landing/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    desc = models.CharField(max_length=60)
   

main_menu/models.py
from django.db import models

# Create your models here.

profilku/models.py
from django.db import models

# Create your models here.

landing/forms.py
from django import forms

class StatusForm(forms.Form):
    errors = {
        'description': 'Tolong isi input ini',
    }
    attrs = {
        'class':'status-form-input',
        'placeholder':'What is on your mind?',
    }
    desc = forms.CharField(label="",max_length=60, widget=forms.Textarea(attrs=attrs),
        required=True)

landing/views.py
from django.shortcuts import render
from .forms import StatusForm
from .models import Status
from django.http import HttpResponseRedirect

# Create your views here.
'''
status_page = {}
def index(request):
    return render(request,'landing_page.html', {'status_page':status_page})

def message_post(request):
    form = StatusForm(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['desc'] = request.POST['desc']
        message = StatusForm(desc=response['desc'])
        message.save()

        html = 'landing_page.html'
        return render(request,html,response)
    else:
        return render(request,'landing_page.html',response)
'''
response = {}
def index(request):
    form = StatusForm()
    response['form'] = form
    hasil = Status.objects.all()
    response['result']=hasil
    return render(request, 'landing_page.html', response)

def post(request):
    form = StatusForm(request.POST or None)
    if (request.method == "POST"):
        print(form)
        response['desc'] = request.POST['desc']
        message = Status(desc=response['desc'])
        message.save()
        
    else:
        print(form.errors)
    
    return HttpResponseRedirect('/landing')

main_menu/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.
response={}

def index(request):
    return render(request,'main.html',response)

profilku/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
# Create your views here.

response={}
def index(request):
    return render(request,'profil.html',response)

landing/templates/landing_page.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hello</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css" /> -->
    <!-- <script src="main.js"></script> -->
</head>
<body>
    Hello! Apa kabar!

    
    <form id="form" action='posted'method='POST'>
        {%csrf_token%}
        {{form}}

        <button id="submit" class="btn btn-primary" type="submit" form="form" value="Submit">Submit</button>
    </form>

    <table class="table">
        <thead>
            <th>Status</th>
        </thead>
        <tbody>
            {% for i in result %}
            <tr>
                <td> {{i.desc}} </td>
                
            </tr>
            {% endfor %}
        </tbody>
    </table>


</body>
</html>

main_menu/templates/main.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Issa Main Menu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--  <link rel="stylesheet" href="{% static 'css/main_menu.css' %}" />-->
    <script src="main.js"></script>
</head>
<body>
    <div class="content">
        <a href="{% url 'landing:landing' %}" id="form_link">Story 6</a>
        <br>
        <a href="{% url 'profilku:profilku' %}" id="challenge_link">Challenge: Profile Page with TDD</a>
    </div>
    </body>
</html>

profilku/templates/profil.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>My Profile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    Hello, my name is Thia and this is a PPW Challenge<br>
    I am a computer science student at UI<br>
    I would put some style here but i'm not gonna risk it huehuehehu:):):):)<br>

</body>
</html>